// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDDn_6Hs24i8Mder7352kd2HeCjDEdKz4',
    appId: '1:716941319678:web:0276d13c02ea324c1df4af',
    messagingSenderId: '716941319678',
    projectId: 'my-ecommerce-app-123-e4eb8',
    authDomain: 'my-ecommerce-app-123-e4eb8.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-e4eb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Sb6vBE1x4tS01D4xwK1ynqGRA0cnOBE',
    appId: '1:716941319678:android:bd0375d9f88eec1a1df4af',
    messagingSenderId: '716941319678',
    projectId: 'my-ecommerce-app-123-e4eb8',
    storageBucket: 'my-ecommerce-app-123-e4eb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeKEL9hV1xnErFn5mJghFeA69CY9hdSiI',
    appId: '1:716941319678:ios:48dadd143e80059b1df4af',
    messagingSenderId: '716941319678',
    projectId: 'my-ecommerce-app-123-e4eb8',
    storageBucket: 'my-ecommerce-app-123-e4eb8.firebasestorage.app',
    iosBundleId: 'com.example.ecommersApp',
  );
}
